dist: xenial
language: bash
env:
  global:
    - TEST_CMD='script/run test.sh'

.com.github.junaruga.switch-module-stream-matrix-definitions:
  - &test_in_container
    install: |
      docker build --rm -t test/fedora -f ci/Dockerfile-fedora \
        --build-arg MODULE_NAME=${MODULE_NAME} \
        --build-arg CUR_STREAM=${CUR_STREAM} \
        --build-arg NEW_STREAM=${NEW_STREAM} \
        --build-arg MODULE_PROFILE=${MODULE_PROFILE} \
        .
    script: |
      docker run --rm -t test/fedora ${TEST_CMD}

matrix:
  include:
    - env:
        - MODULE_NAME=ruby
        - CUR_STREAM=2.5
        - NEW_STREAM=2.6
      <<: *test_in_container
    - env:
        - MODULE_NAME=ruby
        - CUR_STREAM=2.6
        - NEW_STREAM=2.5
      <<: *test_in_container
    - env:
        - MODULE_NAME=nodejs
        - CUR_STREAM=10
        - NEW_STREAM=12
      <<: *test_in_container
    - env:
        - MODULE_NAME=perl
        - CUR_STREAM=5.26
        - NEW_STREAM=5.30
        # Need to set a profile as perl module does not have a default profile.
        - MODULE_PROFILE=default
      <<: *test_in_container
    - env:
        - MODULE_NAME=perl
        - CUR_STREAM=5.30
        - NEW_STREAM=5.26
        - MODULE_PROFILE=default
      <<: *test_in_container
  allow_failures:
  fast_finish: true
branches:
  only:
    - master
    # Enable "test/*" and "pull/*" branches to run Travis CI
    # on forked repository.
    - /^test\//
    - /^pull\//
