dist: xenial
language: bash
env:
  global:
    - BASE_IMAGE=fedora:30
    - TEST_CMD='script/run test.sh'

.com.github.junaruga.switch-module-stream-matrix-definitions:
  - &test_in_container
    install: |
      docker build --rm -t test/fedora -f ci/Dockerfile-fedora \
        --build-arg BASE_IMAGE=${BASE_IMAGE} \
        --build-arg MODULE_NAME=${MODULE_NAME} \
        --build-arg CUR_STREAM=${CUR_STREAM} \
        --build-arg NEW_STREAM=${NEW_STREAM} \
        --build-arg MODULE_PROFILE=${MODULE_PROFILE} \
        .
    script: |
      docker run --rm -t test/fedora ${TEST_CMD}

matrix:
  include:
    - env:
        - BASE_IMAGE=fedora:31
        - MODULE_NAME=ruby
        - CUR_STREAM=2.5
        - NEW_STREAM=2.6
      <<: *test_in_container
    - env:
        - BASE_IMAGE=fedora:31
        - MODULE_NAME=ruby
        - CUR_STREAM=2.6
        - NEW_STREAM=2.5
      <<: *test_in_container
    - env:
        - MODULE_NAME=ruby
        - CUR_STREAM=2.5
        - NEW_STREAM=2.6
        # Need to set a profile as the module does not have a default profile.
        # https://pagure.io/releng/fedora-module-defaults/pull-request/163
        - MODULE_PROFILE=default
      <<: *test_in_container
    # Only 1 stream is available on RHEL 8.0.
    - env:
        - BASE_IMAGE=registry.access.redhat.com/ubi8:8.0
        - MODULE_NAME=ruby
        - CUR_STREAM=2.5
        - NEW_STREAM=2.5
      <<: *test_in_container
    - env:
        - MODULE_NAME=nodejs
        - CUR_STREAM=10
        - NEW_STREAM=12
      <<: *test_in_container
    - env:
        - MODULE_NAME=perl
        - CUR_STREAM=5.28
        - NEW_STREAM=5.30
        # Need to set a profile as the module does not have a default profile.
        - MODULE_PROFILE=default
      <<: *test_in_container
    - env:
        - MODULE_NAME=perl
        - CUR_STREAM=5.30
        - NEW_STREAM=5.28
        - MODULE_PROFILE=default
      <<: *test_in_container
    - env:
        # php module does not exist on Fedora.
        - BASE_IMAGE=registry.access.redhat.com/ubi8:8.0
        - MODULE_NAME=php
        - CUR_STREAM=7.2
        - NEW_STREAM=7.2
      <<: *test_in_container
    - env:
        - BASE_IMAGE=fedora:31
        - MODULE_NAME=nginx
        - CUR_STREAM=1.14
        - NEW_STREAM=1.16
      <<: *test_in_container
    - env:
        - MODULE_NAME=postgresql
        - CUR_STREAM=9.6
        - NEW_STREAM=10
        # Need to set a profile as the module does not have a default profile.
        - MODULE_PROFILE=server
      <<: *test_in_container
  allow_failures:
  fast_finish: true
branches:
  only:
    - master
    # Enable "test/*" and "pull/*" branches to run Travis CI
    # on forked repository.
    - /^test\//
    - /^pull\//
